name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ rohithdocker}}

      # Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: |
          docker build -t living7ston/loginpage .

      # Tag the Docker image with the latest tag and push to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag living7ston/loginpage living7ston/loginpage:latest
          docker push living7ston/loginpage:latest
