name: Run Tests in Docker

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code to the GitHub runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker to build the container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image based on your Dockerfile
      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      # Run tests inside the Docker container
      - name: Run tests in Docker container
        run: |
          docker run --rm my-node-app npm test
          
      # Optionally, you can push the Docker image to Docker Hub or another registry if needed
      # - name: Push Docker image
      #   run: |
      #     docker tag my-node-app your-dockerhub-username/my-node-app:latest
      #     docker push your-dockerhub-username/my-node-app:latest
