name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the version of Node.js (change as needed)

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: |
          npm test  # This will run the Jest tests defined in your package.json
